name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Some task
        id: call
        uses: ./.github/workflows/actions/echo
        with:
          name: "John"
      - run: echo ${{ steps.call.outputs.message }}
