name: Test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Some task
        uses: ./.github/workflows/actions/echo
        env:
          XX: nihaowa
