name: Test
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display Rust version
        run: rustc --version
      - name: Display Cargo version
        run: cargo --version
